### ISSUE TITLE
Guia de uso do Trezentos

### ISSUE THREAD

**Issue by lucasdutraf** [Projeto-Fragelli/Trezentos-App#102]
# Guia de uso do Trezentos

**Descrição**
É necessário uma busca e estudo prévio para elaboração de um guia, claro e objetivo, do uso da aplicação.
**Tarefas**

- [x] Fazer uma pesquisa das melhores formas de fazer um guia para o usuário

- [x] Verificar quais guias aplicar no app

**Critérios de Aceitação**
* Primeira versão do modelo de guia de uso para o Trezentos finalizado

**Comment by lucasdutraf** [comment]
@caiovfernandes @VictorLeviPeixoto Galera, critérios de aceitação prontos! Boa sprint :smile_cat:

**Comment by lucasdutraf** [comment]
Galera, se usarem algum material como referência, deixem aqui para termos esse rastreio!

**Comment by VictorLeviPeixoto** [comment]
https://developer.android.com/training/tv/playback/onboarding
https://www.youtube.com/watch?v=byLKoPgB7yA
https://material.io/design/communication/onboarding.html#self-select-model
