### ISSUE TITLE
Estudar tabela ajudante/ajudado 300

### ISSUE THREAD

**Issue by lucasdutraf** [Projeto-Fragelli/Trezentos-App#110]
# Estudar tabela ajudante/ajudado 300

## **Descrição**
É necessário um estudo prévio a respeito de fórmulas e da tabela utilizada pelo professor Fragelli para aplicar o 300 para que, futuramente, possamos implementá-las no aplicativo.
## **Tarefas**

- [X] Ler a documentação disponibilizada;
- [X] Estudar as fórmulas para calculo de notas;
- [ ] Estudar tabelas de organização de notas;

## **Critérios de Aceitação**
* A dupla responsável deve fazer uma apresentação sobre o que foi levantado para toda a equipe

**Comment by lucasdutraf** [comment]
Galera, se não me engano, a planilha se encontra nesse [link](http://metodo300.com/). Boa sorte!

**Comment by lucasdutraf** [comment]
@guilherme-mendes @GabrielTiveron  Galera, critérios de aceitação prontos! Boa sprint :smile_cat:

**Comment by lucasdutraf** [comment]
Eai, galera! Como anda a issue? Qualquer problema podem me avisar @GabrielTiveron @guilherme-mendes

**Comment by GabrielTiveron** [comment]
[Estudo da tabela ajudante/ajudado](https://github.com/Projeto-Fragelli/Trezentos-App/files/2683569/Projeto.300.pdf)
