### ISSUE TITLE
Criação de teste

### ISSUE THREAD

**Issue by GeovanaRamos** [Projeto-Fragelli/Trezentos-App#32]
-  Erro no toast da criação de teste
- Pode ser um erro só na mensagem ou no backend também
![screenshot_20180618-170657](https://user-images.githubusercontent.com/31005087/41626920-830d3be6-73f4-11e8-902f-258fa3815d66.png)

**Comment by GeovanaRamos** [comment]
Constatei que o erro está na mensagem que a a API retorna.

**Comment by CalebeRios** [comment]
Resolvido na API, se puder testar agora pfvr =)

**Comment by GeovanaRamos** [comment]
Realmente, o problema foi corrigido!
