### ISSUE TITLE
Informações da sala mostram dados zerados

### ISSUE THREAD

**Issue by gabiMSilva** [Projeto-Fragelli/Trezentos-App#39]
## Descrição
Ao clicar em "informações da sala", os dados "tamanho dos grupos", "acrécimo" e "nota de corte" aparecem zerados.

![whatsapp image 2018-06-26 at 09 54 47](https://user-images.githubusercontent.com/36926637/41914019-41631e20-7928-11e8-9070-5bb992f3a8f0.jpeg)

**Comment by CalebeRios** [comment]
Isso é um problema da API, ou a API está retornando certo?

**Comment by GeovanaRamos** [comment]
Se você olhar a função **getUserClassFromJson** do **UserClassControl** vai ver que ela não pega esses dados que estão faltando, mas eu tentei puxar esses dados pelo JSON assim como os outros que estão lá e ele retorna NULL. 

Além disso, na função **getCreateClassParams** ele só está enviando nota de corte, mas mesmo acresentando os outros eles ainda aparecem zerados como no print.

**Comment by GeovanaRamos** [comment]
@CalebeRios se eu acrescentar a ultima linha do código assim:
.
.
userClass.setCreationDate(jsonObject.getString("classCreationDate"));
**userClass.setCutOff(Float.parseFloat(jsonObject.getString("classCutOff")));**

Eu recebo o erro:
W/System.err: org.json.JSONException: No value for classCutOff
