### ISSUE TITLE
Persistência dos dados do usuário antigo no usuário atual

### ISSUE THREAD

**Issue by joberthrogers18** [Projeto-Fragelli/Trezentos-App#40]
Quando a pessoa loga e faz suas atividade de criar sala ou apenas visualizar, e depois desloga para logar com outro usuário no app. As informações antigas como: as salas que o usuário antigo está cadastrado aparecem para o usuário atual como  o mesmo fosse o antigo.

**Comment by GeovanaRamos** [comment]
Corrigi no pr do login
