### ISSUE TITLE
Usuário pode fazer cadastro com e-mail já existente

### ISSUE THREAD

**Issue by joberthrogers18** [Projeto-Fragelli/Trezentos-App#42]
Não há nenhuma validação para verificar se há um e-mail igual ao cadastrado, além disso o cadastro quando há esse tipo de situação ainda é efetuado.

**Comment by CalebeRios** [comment]
A API não esta cadastrando quando já tem um email cadastrado. Certeza que ele esta cadastrando um user mesmo com o email repetido?
