### ISSUE TITLE
Estudar sobre notificações

### ISSUE THREAD

**Issue by lucasdutraf** [Projeto-Fragelli/Trezentos-App#89]
**Descrição**
Issue destinada ao estudo sobre notificações utilizando o Android Studio
 
**Critérios de Aceitação**
- [ ] Todos os materiais fontes deverão ser colocados como comentários dessa issue.
- [ ] Ao final dessa issue deverá ser apresentado um compilado com todas as informações recolhidas, em formato de apresentação.

**Comment by lucasdutraf** [comment]
@Projeto-Fragelli/trezentos o que acham dessa issue pra fechar essa semana? Se atentem aos critérios de aceitação.

**Comment by caiovfernandes** [comment]
Por mim tudo bem.
