### ISSUE TITLE
Login utilizando Facebook

### ISSUE THREAD

**Issue by lucasdutraf** [Projeto-Fragelli/Trezentos-App#94]
**Descrição**
Segundo o professor Fragelli, ele não está conseguindo logar utilizando o Facebook e apresentou o seguinte erro.
![whatsapp image 2018-11-14 at 06 40 00](https://user-images.githubusercontent.com/31940073/48517992-473c6180-e84f-11e8-9205-34c1d0b58437.jpeg)

**Tarefas**

**Critérios de Aceitação**

**Comment by lucasdutraf** [comment]
Confiram, por favor, se com vocês acontece o mesmo @guilherme-mendes @pedro-prp @VictorLeviPeixoto @caiovfernandes

**Comment by guilherme-mendes** [comment]
Consegui logar normalmente com o Facebook @lucasdutraf

**Comment by caiovfernandes** [comment]
Primeiro erro: Ao informar credenciais e aceitar o acesso ao Facebook o app trava e fecha inesperadamente
![screenshot_2018-11-15-18-49-18](https://user-images.githubusercontent.com/42192251/48642977-8ee4f980-e9c5-11e8-8d50-8c24a429c78b.png)
.


Segundo erro: Ao reabrir o app, ele estava logado e linkado ao Facebook, porém não utilizou as informações do mesmo criar um usuário no app.
![screenshot_2018-11-15-18-49-32](https://user-images.githubusercontent.com/42192251/48643125-0dda3200-e9c6-11e8-97b0-ee65ec0872db.png)


Aparelho utilizado: Galaxy Note com android 4.4.2.

**Comment by lucasdutraf** [comment]
Algum de vocês já teve contato com a API do facebook? @Projeto-Fragelli/trezentos

**Comment by guilherme-mendes** [comment]
Realizei testes utilizando um Moto G (2ª Geração), versão 5.0.2 do Android, e em um virtual device (Nexus 4, Android 8.1) e consegui logar normalmente com o facebook. Por serem modelos defasados, podem haver divergências com os demais. Peço para que testem novamente em seus respectivos aparelhos para que possa ser solucionado o problema.
![screenshot_2019-01-31-21-45-04](https://user-images.githubusercontent.com/37874689/52093430-4d1a2700-25a2-11e9-84c1-179001534890.png)
![screenshot_2019-01-31-21-45-21](https://user-images.githubusercontent.com/37874689/52093453-615e2400-25a2-11e9-9b73-bc4d4942df79.png)

**Comment by lucasdutraf** [comment]
Interessante. Peço que todos testem essa funcionalidade com a versão mais atualizada da _develop_ e comentem aqui o resultado @Projeto-Fragelli/trezentos

**Comment by lucasdutraf** [comment]
Testei aqui e não apresentou nenhum erro. Versão do android: 6.0 / Modelo: Moto G (3ª geração).

**Comment by pedro-prp** [comment]
Acabei de realizar o teste em um Moto G(1 ger.) Android 7.1.2
Funcionou perfeitamente.

![2019-02-01 00 13 32](https://user-images.githubusercontent.com/32720946/52098509-66c56980-25b6-11e9-89ad-f938c761cd28.jpg)
![2019-02-01 00 13 42](https://user-images.githubusercontent.com/32720946/52098520-6dec7780-25b6-11e9-9172-d450f684bd02.jpg)
